name: Node CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    steps:
    
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ./engine/node_modules
        key: npm-${{ hashFiles('**/package-lock.json') }}
    - name: npm test
      run: rm package-lock.json
      working-directory: ./engine
      env:
        CI: true
